"""films table created

Revision ID: f01b86e71b0b
Revises: 
Create Date: 2025-02-03 15:51:34.900094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01b86e71b0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_films_description'), 'films', ['description'], unique=False)
    op.create_index(op.f('ix_films_id'), 'films', ['id'], unique=False)
    op.create_index(op.f('ix_films_rating'), 'films', ['rating'], unique=False)
    op.create_index(op.f('ix_films_release_date'), 'films', ['release_date'], unique=False)
    op.create_index(op.f('ix_films_title'), 'films', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_films_title'), table_name='films')
    op.drop_index(op.f('ix_films_release_date'), table_name='films')
    op.drop_index(op.f('ix_films_rating'), table_name='films')
    op.drop_index(op.f('ix_films_id'), table_name='films')
    op.drop_index(op.f('ix_films_description'), table_name='films')
    op.drop_table('films')
    # ### end Alembic commands ###
